general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    cloudFoundryDeploy:
        deployTool: 'mtaDeployPlugin'
        deployType: 'standard'
        cloudFoundry:
          org: 'p2001383561trial'
          space: 'qa'
          credentialsId: 'CF_CREDENTIALSID'
  seleniumExecuteTests:
    buildTool: 'npm'
    containerPortMappings:
      'selenium/standalone-chrome':
        - containerPort: 4444
          hostPort: 4444
    failOnError: true
    sidecarImage: 'selenium/standalone-chrome'
    sidecarName: 'selenium'
    sidecarVolumeBind:
      '/dev/shm': '/dev/shm'
    stashContent:
      - 'tests'
    maven:
      dockerImage: 'maven:3.5-jdk-8'
      dockerName: 'maven'
      dockerWorkspace: ''
    npm:
      dockerImage: 'node:lts-stretch'
      dockerName: 'npm'
      dockerWorkspace: '/home/node'
    bundler:
      dockerImage: 'ruby:2.5.3-stretch'
      dockerName: 'bundler'
      dockerWorkspace: ''
  uiVeri5ExecuteTests:
    failOnError: false
    dockerEnvVars: {}
    installCommand: 'npm install @ui5/uiveri5 --global --quiet'
    seleniumPort: 4444
    stashContent:
      - 'buildDescriptor'
      - 'tests'
    testOptions: ''
    runCommand: "uiveri5 --seleniumAddress='http://${config.seleniumHost}:${config.seleniumPort}/wd/hub'"